apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      initContainers:
        - name: wait-for-nats
          image: busybox:1.28
          command: [ 'sh', '-c', 'until nc -z nats-srv 4222; do echo waiting for nats-srv; sleep 2; done;' ]
        - name: wait-for-mongo
          image: busybox:1.28
          command: [ 'sh', '-c', 'until nc -z tickets-mongo-srv 27017; do echo waiting for tickets-mongo-srv; sleep 2; done;' ]
      containers:
        - name: tickets
          image: fail1950/tickets
          env:
            - name: NATS_STREAM_NAME_FOR_PUBLISH
              value: "TICKETS"
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: MONGO_URI
              value: "mongodb://tickets-mongo-srv:27017/tickets"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000